ensure gitlabCI using new enough gcc

diff --git a/tests/gitlab/gitlab-ci.yml b/tests/gitlab/gitlab-ci.yml
--- a/tests/gitlab/gitlab-ci.yml
+++ b/tests/gitlab/gitlab-ci.yml
@@ -26,6 +26,15 @@ stages:
 
 .build_cpu:
     before_script:
+        - |- 
+            if [ "$ci_c_cmp" != "gcc" ]; then
+                module --latest load gcc
+                if (( $(gcc -dumpversion | sed 's/\..*//') < 5 )); then
+                    echo "unable to find new enough gcc to support ${ci_c_cmp} build"
+                    exit 1
+                fi
+                export GXX_PATH=$(dirname $(which gcc))/../
+            fi
         - module reset
         - module load $ci_cmake
         - module load $ci_cmp_mod
@@ -50,8 +59,15 @@ stages:
     script:
         - mkdir build
         - cd build
-        - cmake -DBUILD_TESTING_FULL=ON -DBUILD_UTILITIES=OFF -DZFP_WITH_CUDA=OFF ${ci_cmake_flags} ..
-        - make -j
+        - |-
+            if [ "$ci_c_cmp" == "intel" ]; then
+                export GXX_ROOT=${GXX_PATH}/bin/
+                export GXX_INCLUDE=${GXX_PATH}/include/
+            elif ["$ci_c_cmp" == "clang" ]; then
+                export ci_cmake_cmp_flags="-DCMAKE_CXX_FLAGS=--gcc-toolchain=${GXX_PATH} -DCMAKE_C_FLAGS=--gcc-toolchain=${GXX_PATH}"
+            fi
+        - cmake -DBUILD_TESTING_FULL=ON -DBUILD_UTILITIES=OFF -DZFP_WITH_CUDA=OFF ${ci_cmake_flags} ${ci_cmake_cmp_flags} ..
+        - cmake --build .
     extends: [.build]
 
 .build_gpu:
